### ISSUE TITLE
Support std::mdspan

### ISSUE THREAD

**Issue by certik** [lcompilers/lc#14]

**Comment by czgdp1807** [comment]
`std::mdspan` will come with C++23 support. That isn't released in `compilers` package of conda. And is also not there in my system's clang.

**Comment by czgdp1807** [comment]
Can be closed after https://github.com/lcompilers/lc/pull/115 is merged. There is not much useful to `std::mdspan` after `submdspan` support. Array operations can't be done on std::mdspan the same way as in Fortran or using `xtensor`. I would support `PyTorch` tensors next. That's most important for AI related use cases.
