### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by certik** [lcompilers/lc#36]
These are not blockers, but would be good to fix soon to avoid technical debt:

* [x] #34
* [x] #37
* [x] #35
* [ ] #31
* [x] #32

**Comment by Shaikh-Ubaid** [comment]
Is this issue safe to close? The last issue left is https://github.com/lcompilers/lc/issues/31, but it is noted at https://github.com/lcompilers/lc/issues/94.

**Comment by certik** [comment]
Thanks!
